<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/user.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        //->prependStylesheet($this->basePath() . '/css/admin.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()                
            ->prependFile($this->basePath() . '/js/jquery.colorbox-min.js')
            ->prependFile($this->basePath() . '/js/user/user.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li> |
                        <!--<li><a href="<?php echo $this->url('admin',array('action' => 'positions')) ?>"><?php echo $this->translate('Positions') ?></a></li>-->
                        <?php if($this->auth) {  ?>
                            <li><a href="<?php echo $this->url('auth',array('action' => 'logout')) ?>"><?php echo $this->translate('Logout') ?></a></li>
                        <?php } else { ?>
                            <li><a href="<?php echo $this->url('auth',array('action' => 'login')) ?>"><?php echo $this->translate('Login') ?></a></li>
                        <?php } ?>                        
                    </ul>
                    <?php if(isset($this->logged_in_as)) { ?>
                        <div style="float:right;color:#fff"> 
                            Logged In As <?php echo $this->logged_in_as;?>
                        </div>
                    <?php } ?>
                </div><!--/.nav-collapse -->
                
            </div>
        </nav>
        <div class="container">
            <div class="videopopup"></div>
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>KS User Panel </p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
