<p> Welcome User </p>
<?php
    //echo 'Base:'.$this->basePath();
    if(!empty($this->positions) && is_array($this->positions)) {
        foreach($this->positions as $p) { ?>
        <div style="border:#00a9e8 solid thin;width: 320px;height: 240px;display: inline-block" disabled="disabled">
            <h4><?php echo $p->work_name;?></h4>        
        <?php
            $file = './public/uploads/admin/'.$p->work_video_list;
            if(file_exists($file)) {
                $info = new SplFileInfo($file);
                $fileext = $info->getExtension();
                $mimetypes = array(
                    'ogv'   =>  'video/ogg',
                    'mp4'   =>  'video/mp4',
                    'webm'  =>  'video/webm',
                    'flv'   =>  'video/x-flv',
                );
                if(in_array($fileext, array('mp4','ogv','webm','flv'))) {
                    // Display video tag
                    //var_dump($p);
                ?>   
                    <video height="160" width="240" id="video<?php echo $p->id;?>">
                        <source src="<?php echo $this->basePath().'/uploads/admin/'.$p->work_video_list;?>" type="<?php echo $mimetypes[$fileext];?>">                    
                    </video>
                    <?php if($p->work_rate == 1) { ?>
                        <input type="button" class="playVideo" id="<?php echo $p->id;?>" value="Play"/>
                        <input type="hidden" id="play-status<?php echo $p->id;?>" value="0" />
                    <?php } ?>
                    <br>
                <?php  
                }
                else {
                    echo 'No Video Uploaded';
                }
                
            } ?>
                </div>
        <?php
        }
    }
?>