<p> Welcome User </p>
<?php
    //echo 'Base:'.$this->basePath();
    if(!empty($this->positions) && is_array($this->positions)) {
        foreach($this->positions as $p) { 
            if($p->isactive == 1) { ?>
            <div class="videotile">
                <h4><?php echo $p->work_name;?></h4>        
            <?php
                $file = './public/uploads/admin/'.$p->work_video_list;
                if(file_exists($file)) {
                    $info = new SplFileInfo($file);
                    $fileext = $info->getExtension();
                    $mimetypes = array(
                        'ogv'   =>  'video/ogg',
                        'mp4'   =>  'video/mp4',
                        'webm'  =>  'video/webm',
                        'flv'   =>  'video/x-flv',
                    );
                    if(in_array($fileext, array('mp4','ogv','webm','flv'))) {
                        // Display video tag
                        //var_dump($p);
                    ?>
                        <div id="videotile<?php echo $p->id;?>">
                            <?php if($p->work_rate == 1) { ?>
                                <video height="160" width="240" id="video<?php echo $p->id;?>" controls>
                            <?php } else { ?>                                 
                                 <video height="160" width="240" id="video<?php echo $p->id;?>">
                            <?php } ?>
                                <source src="<?php echo $this->basePath().'/uploads/admin/'.$p->work_video_list;?>" type="<?php echo $mimetypes[$fileext];?>">                    
                            </video>
                        </div>
                        <br/>
                        <?php if($p->work_rate == 1) { ?>
                                <a href="#" id="<?php echo $p->id;?>" class="play-popup">View InPopup</a>
<!--                            <input type="button" class="playVideo" id="<?php echo $p->id;?>" value="Play"/>
                            <input type="hidden" id="play-status<?php echo $p->id;?>" value="0" />-->
                        <?php } ?>                        
                    <?php  
                    }
                    else {
                        echo 'No Video Uploaded';
                    }

                } ?>
                </div>
        <?php
            }
        }
    }
?>